### ISSUE TITLE
[BUG] 'Copy mods keys' fail to copy mod keys that aren't in a key folder.

### ISSUE THREAD

**Issue by rkfnql322** [Foxlider/FASTER#215] opened 2024-10-16 13:32 UTC
**Describe the bug**  
`Copy mods keys` seems to fail to copy mod keys which has name starting with numbers.

**To Reproduce**  
1. Include some [mods which has mod key name starting with numbers.](https://steamcommunity.com/workshop/filedetails/?id=548021629)
2. Try `Copy mods keys`
3. `11Hz.bikey` fails to be copied into `keys` folder. :(

**Expected behaviour**  
All keys which is required to both server/client should be loaded.

**Actual behaviour**  
`Copy mods keys` seems to fail to copy mod keys which has name starting with numbers.

**Screenshots**  
![image](https://github.com/user-attachments/assets/6fe6899a-3b6a-4be1-9c64-73e54090a249)
This is the mod key which fails to be copied in keys folder.

![image](https://github.com/user-attachments/assets/712dca34-5403-485d-a95e-542b667f79ed)
The key is not included after copy mod keys.

**OS Version (required):**  
 - OS: Windows 10 Pro 64bit 10.0 build 19045
 - FASTER Version 1.9f

**Additional context**  
I think it would be also nice to see message output after `copy mods keys` for debug, or clear feedback.
Which would be great if it includes some numerical data such as `n mod keys out of n mods is copied!` and sometimes `n mod failed to copy mod keys due to some problem`.

**Comment by OverlordZorn** [comment] 2024-10-16 16:20
Issue most likely caused by the mod not being in the mods `keys` folder.

**Comment by rkfnql322** [comment] 2024-10-16 16:24
> Issue most likely caused by the mod not being in the mods `keys` folder.

Seems like this makes sense. 

However I would like to refrain "moding" the mod (to add folder) since I use hash check for further mod security. I can still manually add the key to the appropriate folder, but I think fallback function for these situation would be also nice.

**Comment by OverlordZorn** [comment] 2024-10-16 17:04
![image](https://github.com/user-attachments/assets/4cab830b-9b2d-4762-acc4-2085a4ed53d1)

**Comment by jupster** [comment] 2024-10-17 00:49
Will look at but likely won't fix

**Comment by jupster** [comment] 2024-10-17 11:32
FASTER won't copy keys unless in a folder called `keys` by standard this is normal and won't be changed. 

`default\keys\default.bikey`

**Closed by jupster** 2024-10-17 11:32 UTC
Labels: invalid, wontfix
