### ISSUE TITLE
[BUG] Workshop mods marked as "Up to date" after SteamCMD errors out attempting to download them

### ISSUE THREAD

**Issue by Drift91** [Foxlider/FASTER#32] opened 2021-04-07 13:18 UTC
**Describe the bug**
After the following appeared in my SteamCMD output I found that the mods it was attempting to update were marked as up to date.
```
Starting SteamCMD to update Addon
Redirecting stderr to 'C:\steamcmd\logs\stderr.txt'
[  0%] Checking for available updates...

[----] Verifying installation...

Steam Console Client (c) Valve Corporation
-- type 'quit' to exit --
Loading Steam API...OK.
Logging in user 'Drift_king_91_server' to Steam Public ...

Logged in OK
Waiting for user info...OK
ERROR! Timed out waiting for AppInfo update.

SteamCMD Exited
```
I checked the last modified date of the .pbo files of the mods and none of them were modified recently, indicating to me that they did not in fact update.

**To Reproduce**
Steps to reproduce the behaviour:
Currently unknown. Hopefully the error in the log above will be a valid substitute to reproduction steps.

**Expected behaviour**
For the mods to not be automatically marked as up to date when they failed to update.

**Actual behaviour**
The mods are marked as up to date, when they are in fact not up to date.

**Screenshots**
N/A

**OS Version (required):**
 - OS: [Windows Server 2019 build 1809]
 - Version [1.7b H3]

**Additional context**
I doubt it's relevant, but just in case, here's the mods that failed to update.
https://steamcommunity.com/sharedfiles/filedetails/?id=1660226023
https://steamcommunity.com/sharedfiles/filedetails/?id=2286424681

**Comment by Foxlider** [comment] 2021-04-07 14:09
The status process is a bit off actually. Hopefully will be batter for the next version.
It will check the last updated date from the SteamAPI and compare with last time it was updated successfully. (meaning that steamCMD exited with no errors)
You might have an error because of the fact that Steam cannot contact the API correctly or because the registered time in the config is higher than the time returned by the API.

I'll see if I can replicate but so far no fix for this except manually modifying the mod's last update time in the config

**Comment by diaverso** [comment] 2021-04-10 09:00
Where is the file and the line to change the configuration?
I have the same problem.

**Comment by Foxlider** [comment] 2021-04-10 09:28
Before you start changing the configuration and possibly break FASTER : 

1. Make sure you can reach this website and get the mod informations. If not, there is something blocking access to the steam servers and is probably the cause of the issue.
https://api.steampowered.com/IPublishedFileService/GetDetails/v1?key=89B74BCDEF2493AB2774D8A02D9CED0D&publishedfileids[0]=1660226023

2. Backup your settings with FASTER's Maintenance exe

**Comment by diaverso** [comment] 2021-04-10 16:40
It lets me enter the link without problem and I get the data and I have done the backup.
What else do I have to do?

**Comment by Foxlider** [comment] 2021-04-10 17:12
Navigate to %localappdata%\FoxliCorp\FASTER_somethingsomething
And for each mod in the list replace the value in LocalLastUpdated to 0. 
Be warned that this may break everything. Editing the config manually is NOT a good solution but it's the only one I have so far. Check on Discord for advices from the community

**Closed** 2021-12-24 11:18 UTC
Labels: bug
